# Generated by Django 2.2 on 2019-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancel_url',
            field=models.CharField(default='https://127.0.0.1:8000/', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='success_url',
            field=models.CharField(default='https://127.0.0.1:8000/invoice/success/', max_length=200),
        ),
    ]
